<?php
defined( 'ABSPATH' ) || exit;

class Form_Relay_Admin {
	private $service;
	public function __construct( $service ) { $this->service = $service; }
	public function hooks() { add_action( 'admin_menu', array( $this, 'menu' ) ); add_action( 'admin_init', array( $this, 'actions' ) ); add_action( 'admin_enqueue_scripts', array( $this, 'assets' ) ); }
	public function menu() { add_menu_page( 'Form Relay', 'Form Relay', 'manage_options', 'form-relay', array( $this, 'page' ), 'dashicons-email-alt' ); }
	public function assets( $hook ) {
		if ( 'toplevel_page_form-relay' !== $hook ) { return; }
		wp_enqueue_style( 'form-relay-admin', plugins_url( 'css/admin.css', __FILE__ ), array(), FORM_RELAY_VERSION );
		wp_enqueue_script( 'form-relay-admin', plugins_url( 'js/admin.js', __FILE__ ), array(), FORM_RELAY_VERSION, true );
	}
	public function actions() {
		if ( ! current_user_can( 'manage_options' ) || empty( $_POST['form_relay_action'] ) ) { return; }
		check_admin_referer( 'form_relay_admin' ); $action = sanitize_key( wp_unslash( $_POST['form_relay_action'] ) );
		if ( 'save' === $action ) { $this->save(); } elseif ( 'add_form' === $action ) { $this->add_form(); } elseif ( 'duplicate_form' === $action ) { $this->duplicate_form(); } elseif ( 'toggle_form' === $action ) { $this->toggle_form(); } elseif ( 'delete_form' === $action ) { $this->delete_form(); } elseif ( 'test' === $action ) { $this->test(); }
	}
	private function posted_id() { return sanitize_text_field( isset( $_POST['form_id'] ) ? wp_unslash( $_POST['form_id'] ) : '' ); }
	private function redirect( $id = '', $args = array() ) { if ( $id ) { $args['form_id'] = $id; } wp_safe_redirect( add_query_arg( $args, admin_url( 'admin.php?page=form-relay' ) ) ); exit; }
	private function find_index( $forms, $id ) { foreach ( $forms as $i => $form ) { if ( $form['id'] === $id ) { return $i; } } return false; }
	private function save() {
		$settings = Form_Relay::settings(); $id = $this->posted_id(); $i = $this->find_index( $settings['forms'], $id ); if ( false === $i ) { $this->redirect(); }
		$in = isset( $_POST['form'] ) ? wp_unslash( $_POST['form'] ) : array(); $form = $settings['forms'][ $i ];
		$form['name'] = sanitize_text_field( $in['name'] ); $form['enabled'] = empty( $in['enabled'] ) ? 0 : 1; $form['recipient'] = sanitize_email( $in['recipient'] ); $form['from_name'] = sanitize_text_field( $in['from_name'] ); $form['subject'] = sanitize_text_field( $in['subject'] ); $form['reply_to_field'] = sanitize_text_field( $in['reply_to_field'] );
		$form['success_message'] = sanitize_text_field( $in['success_message'] ); $form['error_message'] = sanitize_text_field( $in['error_message'] ); $form['response_type'] = isset( $in['response_type'] ) && 'page' === $in['response_type'] ? 'page' : 'message'; $form['thank_you_page'] = isset( $in['thank_you_page'] ) ? absint( $in['thank_you_page'] ) : 0; $form['success_classes'] = $this->sanitize_classes( isset( $in['success_classes'] ) ? $in['success_classes'] : '' ); $form['error_classes'] = $this->sanitize_classes( isset( $in['error_classes'] ) ? $in['error_classes'] : '' ); $form['reset_after_success'] = empty( $in['reset_after_success'] ) ? 0 : 1; $form['disable_while_submitting'] = empty( $in['disable_while_submitting'] ) ? 0 : 1; $form['scroll_to_response'] = empty( $in['scroll_to_response'] ) ? 0 : 1; $form['ignored_fields'] = sanitize_textarea_field( $in['ignored_fields'] ); $form['rate_limit'] = max( 1, absint( $in['rate_limit'] ) ); $form['rate_window'] = max( 1, absint( $in['rate_window'] ) ); $form['email_template'] = wp_kses_post( $in['email_template'] ); $form['row_template'] = wp_kses_post( $in['row_template'] );
		$warnings = array(); if ( false === strpos( $form['email_template'], '{{fields}}' ) ) { $warnings[] = 'Your Main Email Template does not contain {{fields}}. Submitted Fields will not appear in the email.'; } if ( false === strpos( $form['row_template'], '{{field_label}}' ) && false === strpos( $form['row_template'], '{{field_value}}' ) ) { $warnings[] = 'Your Field Row Template contains neither {{field_label}} nor {{field_value}}.'; } if ( 'page' === $form['response_type'] && ! $form['thank_you_page'] ) { $warnings[] = 'Select a Thank You Page or switch the successful response back to Thank You Message.'; }
		$settings['forms'][ $i ] = $form; $settings['logging'] = empty( $_POST['logging'] ) ? 0 : 1; update_option( Form_Relay::OPTION, $settings, false ); if ( $warnings ) { set_transient( 'form_relay_notice_' . get_current_user_id(), implode( ' ', $warnings ), 60 ); } $this->redirect( $id, array( 'updated' => 1 ) );
	}
	private function add_form() { $settings = Form_Relay::settings(); $form = Form_Relay::new_form(); $settings['forms'][] = $form; update_option( Form_Relay::OPTION, $settings, false ); $this->redirect( $form['id'], array( 'created' => 1 ) ); }
	private function duplicate_form() { $settings = Form_Relay::settings(); $i = $this->find_index( $settings['forms'], $this->posted_id() ); if ( false === $i ) { $this->redirect(); } $form = $settings['forms'][ $i ]; $form['id'] = Form_Relay::new_form()['id']; $form['name'] .= ' Copy'; $settings['forms'][] = $form; update_option( Form_Relay::OPTION, $settings, false ); $this->redirect( $form['id'], array( 'created' => 1 ) ); }
	private function toggle_form() { $settings = Form_Relay::settings(); $id = $this->posted_id(); $i = $this->find_index( $settings['forms'], $id ); if ( false !== $i ) { $settings['forms'][ $i ]['enabled'] = empty( $settings['forms'][ $i ]['enabled'] ) ? 1 : 0; update_option( Form_Relay::OPTION, $settings, false ); } if ( ! empty( $_POST['return_to_list'] ) ) { $this->redirect( '', array( 'updated' => 1 ) ); } $this->redirect( $id ); }
	private function delete_form() { $settings = Form_Relay::settings(); $id = $this->posted_id(); if ( count( $settings['forms'] ) <= 1 ) { set_transient( 'form_relay_notice_' . get_current_user_id(), 'At least one Form must remain.', 60 ); if ( ! empty( $_POST['return_to_list'] ) ) { $this->redirect(); } $this->redirect( $id ); } $settings['forms'] = array_values( array_filter( $settings['forms'], function( $form ) use ( $id ) { return $form['id'] !== $id; } ) ); update_option( Form_Relay::OPTION, $settings, false ); if ( ! empty( $_POST['return_to_list'] ) ) { $this->redirect( '', array( 'deleted' => 1 ) ); } $this->redirect( $settings['forms'][0]['id'], array( 'deleted' => 1 ) ); }
	private function test() { $settings = Form_Relay::settings(); $id = $this->posted_id(); $i = $this->find_index( $settings['forms'], $id ); $input = json_decode( isset( $_POST['sample_json'] ) ? wp_unslash( $_POST['sample_json'] ) : '', true ); $data = $this->service->normalise( $input ); if ( is_wp_error( $data ) ) { set_transient( 'form_relay_notice_' . get_current_user_id(), $data->get_error_message(), 60 ); $this->redirect( $id ); } $result = $this->service->email( $data, true, $settings['forms'][ $i ] ); set_transient( 'form_relay_notice_' . get_current_user_id(), $result ? 'Test email sent.' : 'Test email could not be sent.', 60 ); $this->redirect( $id ); }

	public function page() {
		$settings = Form_Relay::settings(); $requested = isset( $_GET['form_id'] ) ? sanitize_text_field( wp_unslash( $_GET['form_id'] ) ) : '';
		if ( ! $requested ) { $this->list_page( $settings ); return; }
		$i = $this->find_index( $settings['forms'], $requested ); if ( false === $i ) { $this->list_page( $settings ); return; } $form = $settings['forms'][ $i ]; $uid = get_current_user_id(); $notice = get_transient( 'form_relay_notice_' . $uid ); delete_transient( 'form_relay_notice_' . $uid );
		$sample = wp_json_encode( array( 'form_id' => $form['id'], 'fields' => array( 'name' => 'Jane Smith', 'email' => 'jane@example.com', 'phone' => '07123 456789', 'company' => 'Example Company', 'service' => 'Web Development', 'message' => "I'd like some information about a new website." ), 'meta' => array( 'site_name' => 'Example Website', 'page_title' => 'Contact', 'page_url' => 'https://example.com/contact/' ) ), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES );
		?><div class="wrap form-relay"><h1 class="wp-heading-inline">Edit Form</h1> <form method="post" class="heading-action"><?php wp_nonce_field( 'form_relay_admin' ); ?><button class="page-title-action" name="form_relay_action" value="add_form">Add New Form</button></form> <a class="page-title-action" href="<?php echo esc_url( admin_url( 'admin.php?page=form-relay' ) ); ?>">All Forms</a><hr class="wp-header-end"><?php if ( isset( $_GET['updated'] ) ) : ?><div class="notice notice-success"><p>Form saved.</p></div><?php endif; ?><?php if ( $notice ) : ?><div class="notice notice-warning"><p><?php echo esc_html( $notice ); ?></p></div><?php endif; ?>
		<form method="post" id="form-relay-editor"><?php wp_nonce_field( 'form_relay_admin' ); ?><input type="hidden" name="form_relay_action" value="save"><input type="hidden" name="form_id" value="<?php echo esc_attr( $form['id'] ); ?>"><div class="relay-grid"><section class="relay-card"><h2>Form Settings</h2><?php $this->field( 'Form Name', 'name', $form['name'], 'text', 'The name shown in the Forms list. Renaming does not change the Form ID.' ); ?><label>Form Attribute<code class="form-id">data-form-relay="<?php echo esc_html( $form['id'] ); ?>"</code><span class="description">Add this attribute inside your opening &lt;form&gt; tag, for example: &lt;form data-form-relay="<?php echo esc_attr( $form['id'] ); ?>"&gt;. The generated value does not change when the Form is renamed.</span></label><div class="form-status-control"><strong>Submission Status</strong><label class="check"><input type="checkbox" name="form[enabled]" value="1" <?php checked( $form['enabled'] ); ?>> Accept frontend submissions</label><p class="description">When disabled, this Form remains saved but submissions using its Form ID are rejected with the configured unavailable message.</p></div><?php $this->field( 'Recipient Email', 'recipient', $form['recipient'], 'email' ); $this->field( 'Sender Name', 'from_name', $form['from_name'], 'text', 'Shown as the sender name. The sender email is generated automatically from this WordPress site domain.' ); $this->field( 'Email Subject', 'subject', $form['subject'] ); $this->field( 'Reply-To Field', 'reply_to_field', $form['reply_to_field'], 'text', 'Enter the preferred HTML name attribute for the visitor’s email. If it is missing or invalid, Form Relay automatically uses the first valid submitted email address.' ); ?><h2>Behaviour</h2><label class="check"><input type="checkbox" name="form[reset_after_success]" value="1" <?php checked( $form['reset_after_success'] ); ?>> Reset form after successful submission</label><label class="check"><input type="checkbox" name="form[disable_while_submitting]" value="1" <?php checked( $form['disable_while_submitting'] ); ?>> Disable submit button while submitting</label><label class="check"><input type="checkbox" name="form[scroll_to_response]" value="1" <?php checked( $form['scroll_to_response'] ); ?>> Scroll response message into view</label><h2>Spam / Rate Limiting</h2><label>Ignored Fields<textarea name="form[ignored_fields]" rows="6"><?php echo esc_textarea( $form['ignored_fields'] ); ?></textarea><span class="description">One Submitted Field name per line.</span></label><div class="rate"><label>Submissions<input type="number" min="1" name="form[rate_limit]" value="<?php echo esc_attr( $form['rate_limit'] ); ?>"></label><label>Per minutes<input type="number" min="1" name="form[rate_window]" value="<?php echo esc_attr( $form['rate_window'] ); ?>"></label></div></section>
		<section class="relay-card editors"><h2>Main Email Template</h2><?php $this->insert_buttons( array( 'form_name' => 'Form Name', 'site_name' => 'Site Name', 'page_title' => 'Page Title', 'page_url' => 'Page URL', 'submitted_at' => 'Submitted At', 'fields' => 'Fields' ), 'main-template' ); ?><textarea id="main-template" class="code" name="form[email_template]" rows="18"><?php echo esc_textarea( $form['email_template'] ); ?></textarea><h2>Field Row Template</h2><?php $this->insert_buttons( array( 'field_key' => 'Field Key', 'field_label' => 'Field Label', 'field_value' => 'Field Value' ), 'row-template' ); ?><textarea id="row-template" class="code" name="form[row_template]" rows="10"><?php echo esc_textarea( $form['row_template'] ); ?></textarea></section></div><?php $this->response_settings( $form ); ?><p class="form-actions"><?php submit_button( 'Save Form', 'primary', 'submit', false ); ?> <button type="button" class="button form-relay-modal-preview">Preview Email</button> <button class="button" name="form_relay_action" value="duplicate_form">Duplicate Form</button> <button class="button" name="form_relay_action" value="toggle_form"><?php echo $form['enabled'] ? 'Disable Form' : 'Enable Form'; ?></button> <button class="button button-link-delete confirm-delete" name="form_relay_action" value="delete_form">Delete Form</button></p><label class="check"><input type="checkbox" name="logging" value="1" <?php checked( $settings['logging'] ); ?>> Enable metadata-only submission logging</label></form>
		<?php $this->reference(); $this->message_reference(); ?>
		<section class="relay-card integration"><h2>Integration</h2><p>Add this Integration Attribute to your existing same-site HTML form. Form Relay handles submission and creates the response message automatically.</p><pre id="integration-code">&lt;form data-form-relay="<?php echo esc_html( $form['id'] ); ?>"&gt;</pre><button type="button" class="button copy-integration" data-copy="data-form-relay=&quot;<?php echo esc_attr( $form['id'] ); ?>&quot;">Copy attribute</button><p class="description">No API key, custom JavaScript, custom PHP, or manually-created response container is required.</p></section>
		<section class="relay-card test"><h2>Send Test Email</h2><p>Edit the dummy submission data below, then send a test to the configured recipient.</p><form method="post"><?php wp_nonce_field( 'form_relay_admin' ); ?><input type="hidden" name="form_id" value="<?php echo esc_attr( $form['id'] ); ?>"><textarea class="code" name="sample_json" rows="16"><?php echo esc_textarea( $sample ); ?></textarea><p><button class="button button-primary" name="form_relay_action" value="test">Send Test Email</button></p></form></section><?php $this->preview_modal(); ?></div><?php
	}
	private function list_page( $settings ) {
		$notice = get_transient( 'form_relay_notice_' . get_current_user_id() ); delete_transient( 'form_relay_notice_' . get_current_user_id() );
		?><div class="wrap form-relay form-relay-list"><h1 class="wp-heading-inline">Forms</h1> <form method="post" class="heading-action"><?php wp_nonce_field( 'form_relay_admin' ); ?><button class="page-title-action" name="form_relay_action" value="add_form">Add New Form</button></form><hr class="wp-header-end">
		<?php if ( isset( $_GET['deleted'] ) ) : ?><div class="notice notice-success is-dismissible"><p>Form deleted.</p></div><?php elseif ( isset( $_GET['updated'] ) ) : ?><div class="notice notice-success is-dismissible"><p>Form updated.</p></div><?php endif; ?><?php if ( $notice ) : ?><div class="notice notice-warning"><p><?php echo esc_html( $notice ); ?></p></div><?php endif; ?>
		<p>Manage the forms handled by Form Relay. Select a form name to edit its settings and templates.</p>
		<table class="wp-list-table widefat fixed striped table-view-list forms"><thead><tr><th scope="col" class="column-primary">Form</th><th scope="col">Form ID</th><th scope="col">Recipient</th><th scope="col">Status</th></tr></thead><tbody>
		<?php foreach ( $settings['forms'] as $form ) : $edit_url = add_query_arg( array( 'page' => 'form-relay', 'form_id' => $form['id'] ), admin_url( 'admin.php' ) ); ?><tr><td class="title column-title has-row-actions column-primary" data-colname="Form"><strong><a class="row-title" href="<?php echo esc_url( $edit_url ); ?>"><?php echo esc_html( $form['name'] ); ?></a></strong><div class="row-actions"><span class="edit"><a href="<?php echo esc_url( $edit_url ); ?>">Edit</a> | </span><span class="duplicate"><?php $this->row_action( $form['id'], 'duplicate_form', 'Duplicate' ); ?> | </span><span class="toggle"><?php $this->row_action( $form['id'], 'toggle_form', empty( $form['enabled'] ) ? 'Enable' : 'Disable' ); ?> | </span><span class="trash"><?php $this->row_action( $form['id'], 'delete_form', 'Delete', true ); ?></span></div><button type="button" class="toggle-row"><span class="screen-reader-text">Show more details</span></button></td><td data-colname="Form ID"><code><?php echo esc_html( $form['id'] ); ?></code></td><td data-colname="Recipient"><?php echo esc_html( $form['recipient'] ); ?></td><td data-colname="Status"><span class="form-status form-status--<?php echo empty( $form['enabled'] ) ? 'disabled' : 'enabled'; ?>"><?php echo empty( $form['enabled'] ) ? 'Disabled' : 'Enabled'; ?></span></td></tr><?php endforeach; ?>
		</tbody><tfoot><tr><th scope="col" class="column-primary">Form</th><th scope="col">Form ID</th><th scope="col">Recipient</th><th scope="col">Status</th></tr></tfoot></table></div><?php
	}
	private function row_action( $form_id, $action, $label, $confirm = false ) { ?><form method="post" class="row-action-form"><?php wp_nonce_field( 'form_relay_admin' ); ?><input type="hidden" name="form_id" value="<?php echo esc_attr( $form_id ); ?>"><input type="hidden" name="return_to_list" value="1"><button type="submit" class="button-link <?php echo $confirm ? 'confirm-delete' : ''; ?>" name="form_relay_action" value="<?php echo esc_attr( $action ); ?>"><?php echo esc_html( $label ); ?></button></form><?php }
	private function response_settings( $form ) { ?><section class="relay-card response-settings"><h2>Responses</h2><div class="response-grid"><div><h3>Error Response</h3><?php $this->field( 'Error Message', 'error_message', $form['error_message'], 'text', 'Supports {{error_message}}, {{error_code}} and {{form_name}}. The message is inserted beneath the form.' ); $this->field( 'Error Message Classes', 'error_classes', $form['error_classes'], 'text', 'Optional space-separated CSS classes added to the error message element.' ); ?></div><div><h3>After a Successful Submission</h3><fieldset class="response-choice"><legend class="screen-reader-text">Thank you response type</legend><label><input type="radio" name="form[response_type]" value="message" <?php checked( $form['response_type'], 'message' ); ?>> Show a Thank You Message</label><label><input type="radio" name="form[response_type]" value="page" <?php checked( $form['response_type'], 'page' ); ?>> Redirect to a Thank You Page</label></fieldset><div data-response-panel="message"><?php $this->field( 'Thank You Message', 'success_message', $form['success_message'], 'text', 'Supports {{form_name}}. The message is inserted beneath the form.' ); $this->field( 'Thank You Message Classes', 'success_classes', $form['success_classes'], 'text', 'Optional space-separated CSS classes added to the thank you message element.' ); ?></div><div data-response-panel="page"><label>Thank You Page<?php wp_dropdown_pages( array( 'name' => 'form[thank_you_page]', 'selected' => $form['thank_you_page'], 'show_option_none' => '— Select a page —', 'option_none_value' => '0' ) ); ?><span class="description">Visitors are redirected here after a successful submission.</span></label></div></div></div></section><?php }
	private function sanitize_classes( $classes ) { return implode( ' ', array_values( array_filter( array_map( 'sanitize_html_class', preg_split( '/\s+/', (string) $classes ) ) ) ) ); }
	private function preview_modal() { ?><div id="form-relay-preview-modal" class="form-relay-modal" data-site-name="<?php echo esc_attr( get_bloginfo( 'name' ) ); ?>" hidden><div class="form-relay-modal__backdrop" data-preview-close></div><section class="form-relay-modal__dialog" role="dialog" aria-modal="true" aria-labelledby="form-relay-preview-title"><header><div><h2 id="form-relay-preview-title">Email Preview</h2><p class="description">Rendered with generic dummy submission data. Nothing will be sent.</p></div><button type="button" class="button-link form-relay-modal__close" data-preview-close aria-label="Close preview"><span class="dashicons dashicons-no-alt" aria-hidden="true"></span></button></header><div class="form-relay-modal__status"><span class="spinner is-active"></span> Rendering preview…</div><div class="form-relay-modal__error" role="alert" hidden><p></p></div><iframe class="form-relay-modal__frame" title="Rendered email preview" hidden></iframe><footer><button type="button" class="button" data-preview-close>Close</button></footer></section></div><?php }
	private function field( $label, $key, $value, $type = 'text', $help = '' ) { ?><label><?php echo esc_html( $label ); ?><input type="<?php echo esc_attr( $type ); ?>" name="form[<?php echo esc_attr( $key ); ?>]" value="<?php echo esc_attr( $value ); ?>"><?php if ( $help ) : ?><span class="description"><?php echo esc_html( $help ); ?></span><?php endif; ?></label><?php }
	private function insert_buttons( $items, $target ) { ?><div class="quick-insert" data-target="<?php echo esc_attr( $target ); ?>"><?php foreach ( $items as $placeholder => $label ) : ?><button type="button" class="button button-small" data-placeholder="{{<?php echo esc_attr( $placeholder ); ?>}}"><?php echo esc_html( $label ); ?></button><?php endforeach; ?></div><?php }
	private function reference() { ?><section class="relay-card reference"><h2>Template Placeholder Reference</h2><div class="reference-grid"><div><h3>Main Email Template</h3><dl><dt><code>{{form_name}}</code></dt><dd>The configured name of this Form.</dd><dt><code>{{site_name}}</code></dt><dd>The website name supplied in metadata.</dd><dt><code>{{page_title}}</code></dt><dd>The title of the page containing the Form.</dd><dt><code>{{page_url}}</code></dt><dd>The URL of the page containing the Form.</dd><dt><code>{{submitted_at}}</code></dt><dd>The formatted submission date and time.</dd><dt><code>{{fields}}</code></dt><dd>The concatenated output of the Field Row Template, repeated for every Submitted Field that is not ignored or internal. It is not a single value.</dd></dl><h4>What {{fields}} produces</h4><p>For Submitted Fields <code>name</code>, <code>email</code>, <code>service</code>, and <code>message</code>, this row:</p><pre>&lt;tr&gt;
  &lt;td&gt;&lt;strong&gt;{{field_label}}&lt;/strong&gt;&lt;/td&gt;
  &lt;td&gt;{{field_value}}&lt;/td&gt;
&lt;/tr&gt;</pre><p>is repeated four times, producing rows for Name/Jane Smith, Email/jane@example.com, Service/Web Development, and Message/I’d like to discuss a new website. The combined HTML replaces <code>{{fields}}</code> in the Main Email Template.</p></div><div><h3>Field Row Template</h3><dl><dt><code>{{field_key}}</code></dt><dd>Original HTML Submitted Field name, such as <code>first_name</code>.</dd><dt><code>{{field_label}}</code></dt><dd>Automatically generated readable label; <code>first_name</code> becomes “First Name”.</dd><dt><code>{{field_value}}</code></dt><dd>Sanitised and formatted Submitted Field value, such as “Jane Smith”.</dd></dl><h3>Rendering flow</h3><pre>&lt;form data-form-relay="f_DEMO01"&gt;
  &lt;input name="name"&gt;
  &lt;input name="email"&gt;
  &lt;select name="service"&gt;...&lt;/select&gt;
  &lt;textarea name="message"&gt;&lt;/textarea&gt;
&lt;/form&gt;</pre><p>The Field Row Template is repeated for Name, Email, Service and Message. That generated HTML replaces <code>{{fields}}</code> in the Main Email Template.</p></div></div></section><?php }
	private function message_reference() { ?><section class="relay-card reference"><h2>Success and Error Message Placeholders</h2><div class="reference-grid"><div><h3>Success and Error Messages</h3><dl><dt><code>{{form_name}}</code></dt><dd>The configured Form name. Available in both Success and Error Messages.</dd><dt><code>{{error_message}}</code></dt><dd>A friendly, public-facing description of the submission error. Available only in Error Messages. Internal mail or server details are never inserted.</dd><dt><code>{{error_code}}</code></dt><dd>A predictable machine-readable identifier such as <code>mail_failed</code> or <code>rate_limited</code>. Available only in Error Messages.</dd></dl></div><div><h3>Example Error Message</h3><pre>Sorry, we couldn't process your submission. {{error_message}}</pre><p>For a temporary delivery failure, this might render as:</p><pre>Sorry, we couldn't process your submission. We couldn't send your message right now.</pre><p>Developer filters <code>form_relay_error_code</code> and <code>form_relay_error_message</code> can customise public-safe errors.</p></div></div></section><?php }
}
